def calculate_prediction():
    """
    Simple script to estimate the number of states that will be generated by the solver.
    :return: None
    """

    # Grid Configuration (From main.py)
    TARGET_RINGS = 29  # Default: 29
    TARGET_ANGLES = 21  # Default: 21

    # Solver Configuration
    TARGET_PRUNE_TIME = 10.0  # Default: 100.0 (seconds)

    BASE_RINGS = 29
    BASE_ANGLES = 21
    BASE_TIME_BIN = 100.0
    BASE_STATES = 53159

    STATES_PER_SECOND = 100000

    # Calculate Estimate
    base_node_count = BASE_RINGS * BASE_ANGLES
    target_node_count = TARGET_RINGS * TARGET_ANGLES
    node_multiplier = target_node_count / base_node_count

    time_multiplier = BASE_TIME_BIN / TARGET_PRUNE_TIME

    predicted_states = BASE_STATES * node_multiplier * time_multiplier

    est_seconds = predicted_states / STATES_PER_SECOND

    # Output Results
    print(f"BASELINE:   {BASE_RINGS}x{BASE_ANGLES} Grid, {BASE_TIME_BIN}s bins -> {BASE_STATES:,} states")
    print(f"TARGET:     {TARGET_RINGS}x{TARGET_ANGLES} Grid, {TARGET_PRUNE_TIME}s bins")
    print("-" * 50)
    print(f"PREDICTED STATES:   ~{int(predicted_states):,}")
    print(f"Range:       {int(predicted_states * 0.9):,} to {int(predicted_states * 1.1):,}")
    print(f"Est. Runtime:       {est_seconds:.4f} seconds")
    print("-" * 50)

if __name__ == "__main__":
    calculate_prediction()